# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxivDDjt3cxjAU5F3EqfA-t3EvhrDY35
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Load dataset
df = pd.read_csv("VirtR - Sheet1.csv")

# Title & intro
st.set_page_config(page_title="VR & Pediatric Anxiety Dashboard", layout="wide")
st.title("🩺 VR & Pediatric Anxiety Dashboard")
st.markdown("""
This dashboard explores the effect of **Virtual Reality (VR)** on pre-surgical anxiety in children.
It is based on a small clinical trial dataset, analyzed using Python (Plotly + Streamlit).
""")

# ========== Charts ==========

# Boxplot Anxiety by VR group
fig1 = px.box(df, x='VR', y='Anxiety', color='VR',
              title="Pre-Surgical Anxiety by VR Treatment Group",
              labels={'VR': 'VR Treatment', 'Anxiety': 'Anxiety Score'},
              template='plotly_white')
st.plotly_chart(fig1, use_container_width=True)

# Scatter: Baseline Anxiety vs Pre-Surgical Anxiety
fig2 = px.scatter(df, x='BlueAnx', y='Anxiety', color='VR', trendline='ols',
                  title="Baseline Anxiety vs Pre-Surgical Anxiety",
                  labels={'BlueAnx': 'Baseline Anxiety', 'Anxiety': 'Pre-Surgical Anxiety'},
                  template='plotly_white')
st.plotly_chart(fig2, use_container_width=True)

# Scatter: Age vs Pre-Surgical Anxiety
fig3 = px.scatter(df, x='Age', y='Anxiety', color='VR',
                  title="Age vs Pre-Surgical Anxiety",
                  labels={'Age': 'Child Age', 'Anxiety': 'Pre-Surgical Anxiety'},
                  template='plotly_white')
st.plotly_chart(fig3, use_container_width=True)

# Boxplot for Previous Surgeries subgroup
prev_df = df[df['PrevSurg'] == 'Y']
fig4 = px.box(prev_df, x='VR', y='Anxiety', color='VR',
              title="Anxiety in Children with Previous Surgeries",
              labels={'VR': 'VR Treatment', 'Anxiety': 'Anxiety Score'},
              template='plotly_white')
st.plotly_chart(fig4, use_container_width=True)

# ========== Summary ==========

st.subheader("📊 Summary Statistics by VR Group")
st.write(df.groupby('VR')['Anxiety'].agg(['mean', 'std', 'count']))

st.info("💡 Insight: Baseline anxiety is the strongest predictor of pre-surgical anxiety. "
        "VR shows potential as a calming intervention, but larger trials are needed.")