# -*- coding: utf-8 -*-
"""requirements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jnlGvObVD-MPHdE8WQrcOcM8pxdm-NPL
"""

streamlit
pandas
plotly